# Unformatted Error Output:
# File "tests/__tests__/refmterr/__fixtures__/type_AppliedTooMany/type_AppliedTooMany_3.ml", line 11, characters 5-30:
# Error: The function applied to this argument has type
#          customLogOutputProcessors:(string -> string) list ->
#          customErrorParsers:(string * string list) list -> unit
# This argument cannot be applied with label ~raiseExceptionDuringParse


 ERROR  tests/__tests__/refmterr/__fixtures__/type_AppliedTooMany/type_AppliedTooMany_3.ml:11 5-30 

 8 ┆ let _ =
 9 ┆   parseFromStdin
10 ┆     ~refmttypePath
11 ┆     ~raiseExceptionDuringParse=true
12 ┆     ~customLogOutputProcessors=[]
13 ┆     ~customErrorParsers:[]

The function has type (
  ~customLogOutputProcessors: list(string => string),
  ~customErrorParsers: list((string, list(string)))
) =>
unit

This function doesn't accept an argument named ~raiseExceptionDuringParse.


